# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: "$(VERSION)$(Rev:.r)"
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  projects: '**/DNI.Core.*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: PowerShell@2
    displayName: Update assembly version
    inputs:
     filePath: ./Update-Version.ps1 
     arguments: -fileName "./Directory.Build.props" -version ${Build.BuildNumber}
  - task: DotNetCoreCLI@2
    displayName: Restore project
    inputs:
      command: 'restore'
      projects: $(projects)
  - task: DotNetCoreCLI@2
    displayName: Build project
    inputs:
      command: 'build'
      projects: $(projects)
      arguments: '--no-restore --nologo --configuration Release'
  - task: DotNetCoreCLI@2
    displayName: Pack project for NuGet
    inputs:
      command: 'pack'
      packagesToPack: $(projects)
      nobuild: true
      includesource: true
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'Build.BuildNumber'
